### ISSUE TITLE
Design a more professional logo for the organization

### ISSUE THREAD

**Issue by shakeelmohamed** [flippy-flop/ff-js#2]
What we have now isn't really good enough 😆 
I'm looking for something super simple and minimalist, possibly monochromatic as well.

![image](https://cloud.githubusercontent.com/assets/1480063/19101362/94890084-8a7c-11e6-847c-22772423ce3f.png)

**Comment by versiondrew** [comment]
![flippyflop](https://cloud.githubusercontent.com/assets/19828670/19101659/f1d87970-8a7e-11e6-8bb6-0acc89c3eefb.png)
I threw together something real quick w/ the same color scheme as the one you made.

**Comment by shakeelmohamed** [comment]
Thanks @versiondrew! Can we see a square version? It needs to fit on the organization page: https://github.com/flippy-flop

**Comment by versiondrew** [comment]
![flippyflop2](https://cloud.githubusercontent.com/assets/19828670/19101779/db520a4e-8a7f-11e6-87d6-45e8872dc162.png)

**Comment by lmboricua** [comment]
![flippyfloppylogo](https://cloud.githubusercontent.com/assets/7102177/19101810/cbe4c18a-8a90-11e6-9dfb-647e04fcb070.png)

**Comment by shakeelmohamed** [comment]
@versiondrew it looks a bit stretched vertically

**Comment by shakeelmohamed** [comment]
Closed by #3
